package net.minecraft.lIIIlllIIIllIIIllIII;

import net.minecraft.llIllIlIIIIllIlIIllI.*;
import net.minecraft.IlllllllIIIlIIIlIlII.*;

public class IIllIIllIIIlIlIIIIlI
{
    public static final IlIIIlIlIIIllIlIlIIl llllIIIIlIIIlIlllIll;
    public static final IlIIIlIlIIIllIlIlIIl IlIlIlIlIlllllllllIl;
    public static final IlIIIlIlIIIllIlIlIIl llIllIIIIIllIlIIIIlI;
    public static final IlIIIlIlIIIllIlIlIIl IlIIIlIlIIIllIlIlIIl;
    public static final IlIIIlIlIIIllIlIlIIl IlIlIIIllIllIIIIIllI;
    public static final IIIllllllIllIIIlllIl IllIIlllIIIIlllIIlIl;
    public static final IlIIIlIlIIIllIlIlIIl llllIIIlIlllIlIIIIIl;
    public static final IlIIIlIlIIIllIlIlIIl lIIIIlIIIIIlllIllIII;
    public static final IlIIIlIlIIIllIlIlIIl lIIIlllIIIllIIIllIII;
    public static final IlIIIlIlIIIllIlIlIIl llIIlIIIlIIIllIlIIIl;
    public static final IlIIIlIlIIIllIlIlIIl llIllIlIIIIllIlIIllI;
    public static final IlIIIlIlIIIllIlIlIIl lIlIlIIIllIIllIIIllI;
    public static final IlIIIlIlIIIllIlIlIIl IlIlIIIllIIllIlllllI;
    public static final IlIIIlIlIIIllIlIlIIl IIIIlllIIIIIIlIIIlll;
    public static final IlIIIlIlIIIllIlIlIIl llllIIllllIlIlIIIIll;
    public static final IlIIIlIlIIIllIlIlIIl IlIllIlIlIIIlIlIlIII;
    public static final IlIIIlIlIIIllIlIlIIl IIlllIIlIllIllIlIIll;
    public static final IlIIIlIlIIIllIlIlIIl lllIIIIlllllIlIIllIl;
    public static final IlIIIlIlIIIllIlIlIIl IlIlIIIIIIlllIlIllIl;
    public static final IlIIIlIlIIIllIlIlIIl IIllIIllIIIlIlIIIIlI;
    public static final IlIIIlIlIIIllIlIlIIl IIIlIIIlIlIIlllIIlll;
    public static final IlIIIlIlIIIllIlIlIIl IlIlIIIlIIlIlIIlllIl;
    public static final IlIIIlIlIIIllIlIlIIl IlllllllIIIlIIIlIlII;
    public static final IlIIIlIlIIIllIlIlIIl IIlIIIIlllIlllllIlII;
    public static final IlIIIlIlIIIllIlIlIIl IIIlIIlIIIIlllIlllII;
    public static final IlIIIlIlIIIllIlIlIIl IlIlIllllllllIIIIlII;
    public static final IlIIIlIlIIIllIlIlIIl IIlllIlIIllIlIlIlIIl;
    public static final IlIIIlIlIIIllIlIlIIl llIIIlIlIllIIlIlIlII;
    public static final IlIIIlIlIIIllIlIlIIl lllllIlIIIlIlIIlllII;
    public static final IlIIIlIlIIIllIlIlIIl lIllllllIIllIlIlIlII;
    public static final IlIIIlIlIIIllIlIlIIl llIIlllIIlllIIllIllI;
    public static final IlIIIlIlIIIllIlIlIIl IIlllIIIlIlllIIlllII;
    public static final IlIIIlIlIIIllIlIlIIl IIlIIIIIllIlIIIlIIll;
    public static final IlIIIlIlIIIllIlIlIIl llllllIllIllIlIllllI;
    public static final IlIIIlIlIIIllIlIlIIl IIIllllllIllIIIlllIl;
    public static final IlIIIlIlIIIllIlIlIIl IlIIIlIIIllllIlIlIlI;
    public static final IlIIIlIlIIIllIlIlIIl IIIIIllIIIIlIIIIllIl;
    public static final IlIIIlIlIIIllIlIlIIl IIIIIIIIIlllIllIlIlI;
    public static final IlIIIlIlIIIllIlIlIIl IIllllIIIlIIIIIIllIl;
    public static final IlIIIlIlIIIllIlIlIIl IlllIIIIlIIIlIlIlIIl;
    public static final IlIIIlIlIIIllIlIlIIl lllIllIIIllllllIllll;
    public static final IlIIIlIlIIIllIlIlIIl llIllIlIlIIIIIIIllII;
    public static final IIIlIIlIIIIlllIlllII IIlIlIlIIlIllIIIIIIl;
    public static final IIIlIIlIIIIlllIlllII IllIllIIIIlIIlIlllII;
    public static final IIIlIIlIIIIlllIlllII IlIllllIIlIIlIlIlIll;
    public static final IIIlIIlIIIIlllIlllII IllIllIlllIllllIIllI;
    public static final IIIlIIlIIIIlllIlllII llIlIIIIIlIIlIlIIlll;
    public static final IIIlIIlIIIIlllIlllII IlIIlIlIIIlIIlIlIlII;
    public static final IIIlIIlIIIIlllIlllII IllIlIIllIllIIlIllII;
    public static final IIIlIIlIIIIlllIlllII lIIlIIIlIllIlIllIIIl;
    public static final IIIlIIlIIIIlllIlllII IIlIIIlllIllIllIlIII;
    public static final IIIlIIlIIIIlllIlllII lIlIlIlllIIlIlIlllIl;
    public static final IIIlIIlIIIIlllIlllII llIIIIIIlIllIIlIIIll;
    public static final IIIlIIlIIIIlllIlllII lIIIIlIlIllllIIlIllI;
    public static final IIIlIIlIIIIlllIlllII llIIIlIlllIllIIlIllI;
    public static final IIIlIIlIIIIlllIlllII IlIIllIIllIIllIIlIIl;
    public static final IIIlIIlIIIIlllIlllII lllllIIIIIlIlIIIIIIl;
    public static final IIIlIIlIIIIlllIlllII IllIIlllllIIllIIllIl;
    public static final IIIlIIlIIIIlllIlllII lIllIIIIIlllIIlIIllI;
    public static final IIIlIIlIIIIlllIlllII lIlIIlllIIlIIlIlllIl;
    public static final IIIlIIlIIIIlllIlllII llIIIllIlIllIllIIIIl;
    public static final IIIlIIlIIIIlllIlllII IIIllIIIlIlIIllIIIlI;
    public static final IlIIIlIlIIIllIlIlIIl IIlllIIlllIIIlIlllII;
    public static final IlIIIlIlIIIllIlIlIIl IlIIlllllIIllIIlllll;
    public static final IlIIIlIlIIIllIlIlIIl lllllIIlIlIIIlIlIIIl;
    public static final IlIIIlIlIIIllIlIlIIl IIlllllIllIllIlIlIII;
    public static final IlIIIlIlIIIllIlIlIIl llllIllllIllllIlIlII;
    public static final IlIIIlIlIIIllIlIlIIl IIlIlIllllIlllIIIIll;
    public static final IlIIIlIlIIIllIlIlIIl lIIllIIIllllIlllIllI;
    public static final IlIIIlIlIIIllIlIlIIl IllIlIllIllIlllIIlll;
    public static final IlIIIlIlIIIllIlIlIIl IIllIIIlIIlIlIlIIIII;
    public static final IlIIIlIlIIIllIlIlIIl llIllIIlllllllllllll;
    public static final IlIIIlIlIIIllIlIlIIl lllllIIllIlIllIllllI;
    public static final IlIIIlIlIIIllIlIlIIl IlIIIIIlIIllIIlIlIll;
    public static final IlIIIlIlIIIllIlIlIIl IllllIIlIlIllIIIllII;
    public static final IlIIIlIlIIIllIlIlIIl lllllIIIIIlIIlllIlIl;
    public static final IlIIIlIlIIIllIlIlIIl IlIllllIIIlIllIlIIll;
    public static final IlIIIlIlIIIllIlIlIIl lIIIIIlIlIIIlIIIIlIl;
    public static final IlIIIlIlIIIllIlIlIIl IIllIIIlIIIIlIIlIIII;
    public static final IlIIIlIlIIIllIlIlIIl IIIllIIllIIIIIIlIIlI;
    public static final IlIIIlIlIIIllIlIlIIl IIIIIIIllllIlIIIIIII;
    public static final IlIIIlIlIIIllIlIlIIl IIlllIIIllIllIIlIlIl;
    public static final IlIIIlIlIIIllIlIlIIl llIlllIlllllIIllIIII;
    public static final IlIIIlIlIIIllIlIlIIl lllllIlIlIlllIlllIlI;
    public static final IlIIIlIlIIIllIlIlIIl IlIllllIIlIllIlIlIll;
    public static final IlIIIlIlIIIllIlIlIIl lllIlIIIIIlIlllllIlI;
    public static final IlIIIlIlIIIllIlIlIIl llIlIIIIllIlIIlIlIII;
    public static final IlIIIlIlIIIllIlIlIIl IIIIIlllIlIIIIIIIllI;
    public static final IlIIIlIlIIIllIlIlIIl llllllIIIIIIIlllIIll;
    public static final IlIIIlIlIIIllIlIlIIl IIlIlllIlIlllIlIllll;
    public static final IlIIIlIlIIIllIlIlIIl lIllllIllIllIIllllll;
    public static final IlIIIlIlIIIllIlIlIIl lllIIIIlIlIllIIlIIIl;
    public static final IlIIIlIlIIIllIlIlIIl IllIlllIllIIIIllllII;
    public static final IlIIIlIlIIIllIlIlIIl lIllIlIIIllllllIIlII;
    public static final IlIIIlIlIIIllIlIlIIl IlIllIIllIIlIIIIlIIl;
    public static final lllllIIIIIlIlIIIIIIl lIIlllIlllllIIlllIll;
    public static final IlIIIlIlIIIllIlIlIIl lIllIIlIlIlllllIIIII;
    public static final IlIIIlIlIIIllIlIlIIl lIIlIIIIIIIlIIlIlIIl;
    public static final IlIIIlIlIIIllIlIlIIl IlIIlllIIlIlllllIIlI;
    public static final IlIIIlIlIIIllIlIlIIl llllIlIllllIIlIIlIlI;
    public static final IlIIIlIlIIIllIlIlIIl a;
    public static final IlIIIlIlIIIllIlIlIIl b;
    public static final IlIIIlIlIIIllIlIlIIl c;
    public static final IlIIIlIlIIIllIlIlIIl d;
    public static final IlIIIlIlIIIllIlIlIIl e;
    public static final IlIIIlIlIIIllIlIlIIl f;
    public static final IlIIIlIlIIIllIlIlIIl g;
    public static final IIlllllIllIllIlIlIII h;
    public static final llIlllIlllllIIllIIII i;
    public static final IlIIIlIlIIIllIlIlIIl j;
    public static final IlIIIlIlIIIllIlIlIIl k;
    public static final IlIIIlIlIIIllIlIlIIl l;
    public static final IlIIIlIlIIIllIlIlIIl m;
    public static final IlIIIlIlIIIllIlIlIIl n;
    public static final IlIIIlIlIIIllIlIlIIl o;
    public static final IlIIIlIlIIIllIlIlIIl p;
    public static final IlIIIlIlIIIllIlIlIIl q;
    public static final IlIIIlIlIIIllIlIlIIl r;
    public static final IlIIIlIlIIIllIlIlIIl s;
    public static final IlIIIlIlIIIllIlIlIIl t;
    public static final IlIIIlIlIIIllIlIlIIl u;
    public static final IlIIIlIlIIIllIlIlIIl v;
    public static final IlIIIlIlIIIllIlIlIIl w;
    public static final IlIIIlIlIIIllIlIlIIl x;
    public static final IlIIIlIlIIIllIlIlIIl y;
    public static final IlIIIlIlIIIllIlIlIIl z;
    public static final IlIIIlIlIIIllIlIlIIl A;
    public static final IlIIIlIlIIIllIlIlIIl B;
    public static final IlIIIlIlIIIllIlIlIIl C;
    public static final lllllIIIIIlIIlllIlIl D;
    public static final IlIIIlIlIIIllIlIlIIl E;
    public static final IlIIIlIlIIIllIlIlIIl F;
    public static final IlIIIlIlIIIllIlIlIIl G;
    public static final IlIIIlIlIIIllIlIlIIl H;
    public static final IlIIIlIlIIIllIlIlIIl I;
    public static final IlIIIlIlIIIllIlIlIIl J;
    public static final IlIIIlIlIIIllIlIlIIl K;
    public static final IlIIIlIlIIIllIlIlIIl L;
    public static final IlIIIlIlIIIllIlIlIIl M;
    public static final IlIIIlIlIIIllIlIlIIl N;
    public static final IlIIIlIlIIIllIlIlIIl O;
    public static final IlIIIlIlIIIllIlIlIIl P;
    public static final IlIIIlIlIIIllIlIlIIl Q;
    public static final IlIIIlIlIIIllIlIlIIl R;
    public static final IlIIIlIlIIIllIlIlIIl S;
    public static final IlIIIlIlIIIllIlIlIIl T;
    public static final IlIIIlIlIIIllIlIlIIl U;
    public static final IlIIIlIlIIIllIlIlIIl V;
    public static final IlIIIlIlIIIllIlIlIIl W;
    public static final IlIIIlIlIIIllIlIlIIl X;
    public static final IlIIIlIlIIIllIlIlIIl Y;
    public static final llIlIIIIIlIIlIlIIlll Z;
    public static final IlIIIlIlIIIllIlIlIIl aa;
    public static final IlIIIlIlIIIllIlIlIIl ab;
    public static final IlIIIlIlIIIllIlIlIIl ac;
    public static final IlIIIlIlIIIllIlIlIIl ad;
    public static final IlIIIlIlIIIllIlIlIIl ae;
    public static final IlIIIlIlIIIllIlIlIIl af;
    public static final IlIIIlIlIIIllIlIlIIl ag;
    public static final IlIIlIlIIIlIIlIlIlII ah;
    public static final IlIIIlIlIIIllIlIlIIl ai;
    public static final IlIIIlIlIIIllIlIlIIl aj;
    public static final IlIIIlIlIIIllIlIlIIl ak;
    public static final IlIIIlIlIIIllIlIlIIl al;
    public static final IlIIIlIlIIIllIlIlIIl am;
    public static final llIIIlIlIllIIlIlIlII an;
    public static final IlIIIlIlIIIllIlIlIIl ao;
    public static final IlIIIlIlIIIllIlIlIIl ap;
    public static final IlIIIlIlIIIllIlIlIIl aq;
    public static final IlIIIlIlIIIllIlIlIIl ar;
    public static final IlIIIlIlIIIllIlIlIIl as;
    public static final IlIIIlIlIIIllIlIlIIl at;
    public static final IlIIIlIlIIIllIlIlIIl au;
    public static final IlIIIlIlIIIllIlIlIIl av;
    public static final IlIIIlIlIIIllIlIlIIl aw;
    public static final IlIIIlIlIIIllIlIlIIl ax;
    public static final IlIIIlIlIIIllIlIlIIl ay;
    public static final IlIIIlIlIIIllIlIlIIl az;
    public static final IlIIIlIlIIIllIlIlIIl aA;
    public static final IlIIIlIlIIIllIlIlIIl aB;
    public static final IlIIIlIlIIIllIlIlIIl aC;
    public static final IlIIIlIlIIIllIlIlIIl aD;
    public static final IlIIIlIlIIIllIlIlIIl aE;
    public static final IlIIIlIlIIIllIlIlIIl aF;
    public static final IlIIIlIlIIIllIlIlIIl aG;
    public static final IlIIIlIlIIIllIlIlIIl aH;
    public static final IlIIIlIlIIIllIlIlIIl aI;
    
    static {
        if (!net.minecraft.lIIIlllIIIllIIIllIII.IlIlIlIlIlllllllllIl.llllIIIIlIIIlIlllIll()) {
            throw new RuntimeException("Accessed Items before Bootstrap!");
        }
        llllIIIIlIIIlIlllIll = llllIIIIlIIIlIlllIll("iron_shovel");
        IlIlIlIlIlllllllllIl = llllIIIIlIIIlIlllIll("iron_pickaxe");
        llIllIIIIIllIlIIIIlI = llllIIIIlIIIlIlllIll("iron_axe");
        IlIIIlIlIIIllIlIlIIl = llllIIIIlIIIlIlllIll("flint_and_steel");
        IlIlIIIllIllIIIIIllI = llllIIIIlIIIlIlllIll("apple");
        IllIIlllIIIIlllIIlIl = (IIIllllllIllIIIlllIl)llllIIIIlIIIlIlllIll("bow");
        llllIIIlIlllIlIIIIIl = llllIIIIlIIIlIlllIll("arrow");
        lIIIIlIIIIIlllIllIII = llllIIIIlIIIlIlllIll("coal");
        lIIIlllIIIllIIIllIII = llllIIIIlIIIlIlllIll("diamond");
        llIIlIIIlIIIllIlIIIl = llllIIIIlIIIlIlllIll("iron_ingot");
        llIllIlIIIIllIlIIllI = llllIIIIlIIIlIlllIll("gold_ingot");
        lIlIlIIIllIIllIIIllI = llllIIIIlIIIlIlllIll("iron_sword");
        IlIlIIIllIIllIlllllI = llllIIIIlIIIlIlllIll("wooden_sword");
        IIIIlllIIIIIIlIIIlll = llllIIIIlIIIlIlllIll("wooden_shovel");
        llllIIllllIlIlIIIIll = llllIIIIlIIIlIlllIll("wooden_pickaxe");
        IlIllIlIlIIIlIlIlIII = llllIIIIlIIIlIlllIll("wooden_axe");
        IIlllIIlIllIllIlIIll = llllIIIIlIIIlIlllIll("stone_sword");
        lllIIIIlllllIlIIllIl = llllIIIIlIIIlIlllIll("stone_shovel");
        IlIlIIIIIIlllIlIllIl = llllIIIIlIIIlIlllIll("stone_pickaxe");
        IIllIIllIIIlIlIIIIlI = llllIIIIlIIIlIlllIll("stone_axe");
        IIIlIIIlIlIIlllIIlll = llllIIIIlIIIlIlllIll("diamond_sword");
        IlIlIIIlIIlIlIIlllIl = llllIIIIlIIIlIlllIll("diamond_shovel");
        IlllllllIIIlIIIlIlII = llllIIIIlIIIlIlllIll("diamond_pickaxe");
        IIlIIIIlllIlllllIlII = llllIIIIlIIIlIlllIll("diamond_axe");
        IIIlIIlIIIIlllIlllII = llllIIIIlIIIlIlllIll("stick");
        IlIlIllllllllIIIIlII = llllIIIIlIIIlIlllIll("bowl");
        IIlllIlIIllIlIlIlIIl = llllIIIIlIIIlIlllIll("mushroom_stew");
        llIIIlIlIllIIlIlIlII = llllIIIIlIIIlIlllIll("golden_sword");
        lllllIlIIIlIlIIlllII = llllIIIIlIIIlIlllIll("golden_shovel");
        lIllllllIIllIlIlIlII = llllIIIIlIIIlIlllIll("golden_pickaxe");
        llIIlllIIlllIIllIllI = llllIIIIlIIIlIlllIll("golden_axe");
        IIlllIIIlIlllIIlllII = llllIIIIlIIIlIlllIll("string");
        IIlIIIIIllIlIIIlIIll = llllIIIIlIIIlIlllIll("feather");
        llllllIllIllIlIllllI = llllIIIIlIIIlIlllIll("gunpowder");
        IIIllllllIllIIIlllIl = llllIIIIlIIIlIlllIll("wooden_hoe");
        IlIIIlIIIllllIlIlIlI = llllIIIIlIIIlIlllIll("stone_hoe");
        IIIIIllIIIIlIIIIllIl = llllIIIIlIIIlIlllIll("iron_hoe");
        IIIIIIIIIlllIllIlIlI = llllIIIIlIIIlIlllIll("diamond_hoe");
        IIllllIIIlIIIIIIllIl = llllIIIIlIIIlIlllIll("golden_hoe");
        IlllIIIIlIIIlIlIlIIl = llllIIIIlIIIlIlllIll("wheat_seeds");
        lllIllIIIllllllIllll = llllIIIIlIIIlIlllIll("wheat");
        llIllIlIlIIIIIIIllII = llllIIIIlIIIlIlllIll("bread");
        IIlIlIlIIlIllIIIIIIl = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("leather_helmet");
        IllIllIIIIlIIlIlllII = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("leather_chestplate");
        IlIllllIIlIIlIlIlIll = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("leather_leggings");
        IllIllIlllIllllIIllI = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("leather_boots");
        llIlIIIIIlIIlIlIIlll = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("chainmail_helmet");
        IlIIlIlIIIlIIlIlIlII = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("chainmail_chestplate");
        IllIlIIllIllIIlIllII = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("chainmail_leggings");
        lIIlIIIlIllIlIllIIIl = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("chainmail_boots");
        IIlIIIlllIllIllIlIII = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("iron_helmet");
        lIlIlIlllIIlIlIlllIl = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("iron_chestplate");
        llIIIIIIlIllIIlIIIll = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("iron_leggings");
        lIIIIlIlIllllIIlIllI = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("iron_boots");
        llIIIlIlllIllIIlIllI = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("diamond_helmet");
        IlIIllIIllIIllIIlIIl = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("diamond_chestplate");
        lllllIIIIIlIlIIIIIIl = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("diamond_leggings");
        IllIIlllllIIllIIllIl = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("diamond_boots");
        lIllIIIIIlllIIlIIllI = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("golden_helmet");
        lIlIIlllIIlIIlIlllIl = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("golden_chestplate");
        llIIIllIlIllIllIIIIl = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("golden_leggings");
        IIIllIIIlIlIIllIIIlI = (IIIlIIlIIIIlllIlllII)llllIIIIlIIIlIlllIll("golden_boots");
        IIlllIIlllIIIlIlllII = llllIIIIlIIIlIlllIll("flint");
        IlIIlllllIIllIIlllll = llllIIIIlIIIlIlllIll("porkchop");
        lllllIIlIlIIIlIlIIIl = llllIIIIlIIIlIlllIll("cooked_porkchop");
        IIlllllIllIllIlIlIII = llllIIIIlIIIlIlllIll("painting");
        llllIllllIllllIlIlII = llllIIIIlIIIlIlllIll("golden_apple");
        IIlIlIllllIlllIIIIll = llllIIIIlIIIlIlllIll("sign");
        lIIllIIIllllIlllIllI = llllIIIIlIIIlIlllIll("wooden_door");
        IllIlIllIllIlllIIlll = llllIIIIlIIIlIlllIll("spruce_door");
        IIllIIIlIIlIlIlIIIII = llllIIIIlIIIlIlllIll("birch_door");
        llIllIIlllllllllllll = llllIIIIlIIIlIlllIll("jungle_door");
        lllllIIllIlIllIllllI = llllIIIIlIIIlIlllIll("acacia_door");
        IlIIIIIlIIllIIlIlIll = llllIIIIlIIIlIlllIll("dark_oak_door");
        IllllIIlIlIllIIIllII = llllIIIIlIIIlIlllIll("bucket");
        lllllIIIIIlIIlllIlIl = llllIIIIlIIIlIlllIll("water_bucket");
        IlIllllIIIlIllIlIIll = llllIIIIlIIIlIlllIll("lava_bucket");
        lIIIIIlIlIIIlIIIIlIl = llllIIIIlIIIlIlllIll("minecart");
        IIllIIIlIIIIlIIlIIII = llllIIIIlIIIlIlllIll("saddle");
        IIIllIIllIIIIIIlIIlI = llllIIIIlIIIlIlllIll("iron_door");
        IIIIIIIllllIlIIIIIII = llllIIIIlIIIlIlllIll("redstone");
        IIlllIIIllIllIIlIlIl = llllIIIIlIIIlIlllIll("snowball");
        llIlllIlllllIIllIIII = llllIIIIlIIIlIlllIll("boat");
        lllllIlIlIlllIlllIlI = llllIIIIlIIIlIlllIll("leather");
        IlIllllIIlIllIlIlIll = llllIIIIlIIIlIlllIll("milk_bucket");
        lllIlIIIIIlIlllllIlI = llllIIIIlIIIlIlllIll("brick");
        llIlIIIIllIlIIlIlIII = llllIIIIlIIIlIlllIll("clay_ball");
        IIIIIlllIlIIIIIIIllI = llllIIIIlIIIlIlllIll("reeds");
        llllllIIIIIIIlllIIll = llllIIIIlIIIlIlllIll("paper");
        IIlIlllIlIlllIlIllll = llllIIIIlIIIlIlllIll("book");
        lIllllIllIllIIllllll = llllIIIIlIIIlIlllIll("slime_ball");
        lllIIIIlIlIllIIlIIIl = llllIIIIlIIIlIlllIll("chest_minecart");
        IllIlllIllIIIIllllII = llllIIIIlIIIlIlllIll("furnace_minecart");
        lIllIlIIIllllllIIlII = llllIIIIlIIIlIlllIll("egg");
        IlIllIIllIIlIIIIlIIl = llllIIIIlIIIlIlllIll("compass");
        lIIlllIlllllIIlllIll = (lllllIIIIIlIlIIIIIIl)llllIIIIlIIIlIlllIll("fishing_rod");
        lIllIIlIlIlllllIIIII = llllIIIIlIIIlIlllIll("clock");
        lIIlIIIIIIIlIIlIlIIl = llllIIIIlIIIlIlllIll("glowstone_dust");
        IlIIlllIIlIlllllIIlI = llllIIIIlIIIlIlllIll("fish");
        llllIlIllllIIlIIlIlI = llllIIIIlIIIlIlllIll("cooked_fish");
        a = llllIIIIlIIIlIlllIll("dye");
        b = llllIIIIlIIIlIlllIll("bone");
        c = llllIIIIlIIIlIlllIll("sugar");
        d = llllIIIIlIIIlIlllIll("cake");
        e = llllIIIIlIIIlIlllIll("bed");
        f = llllIIIIlIIIlIlllIll("repeater");
        g = llllIIIIlIIIlIlllIll("cookie");
        h = (IIlllllIllIllIlIlIII)llllIIIIlIIIlIlllIll("filled_map");
        i = (llIlllIlllllIIllIIII)llllIIIIlIIIlIlllIll("shears");
        j = llllIIIIlIIIlIlllIll("melon");
        k = llllIIIIlIIIlIlllIll("pumpkin_seeds");
        l = llllIIIIlIIIlIlllIll("melon_seeds");
        m = llllIIIIlIIIlIlllIll("beef");
        n = llllIIIIlIIIlIlllIll("cooked_beef");
        o = llllIIIIlIIIlIlllIll("chicken");
        p = llllIIIIlIIIlIlllIll("cooked_chicken");
        q = llllIIIIlIIIlIlllIll("mutton");
        r = llllIIIIlIIIlIlllIll("cooked_mutton");
        s = llllIIIIlIIIlIlllIll("rabbit");
        t = llllIIIIlIIIlIlllIll("cooked_rabbit");
        u = llllIIIIlIIIlIlllIll("rabbit_stew");
        v = llllIIIIlIIIlIlllIll("rabbit_foot");
        w = llllIIIIlIIIlIlllIll("rabbit_hide");
        x = llllIIIIlIIIlIlllIll("rotten_flesh");
        y = llllIIIIlIIIlIlllIll("ender_pearl");
        z = llllIIIIlIIIlIlllIll("blaze_rod");
        A = llllIIIIlIIIlIlllIll("ghast_tear");
        B = llllIIIIlIIIlIlllIll("gold_nugget");
        C = llllIIIIlIIIlIlllIll("nether_wart");
        D = (lllllIIIIIlIIlllIlIl)llllIIIIlIIIlIlllIll("potion");
        E = llllIIIIlIIIlIlllIll("glass_bottle");
        F = llllIIIIlIIIlIlllIll("spider_eye");
        G = llllIIIIlIIIlIlllIll("fermented_spider_eye");
        H = llllIIIIlIIIlIlllIll("blaze_powder");
        I = llllIIIIlIIIlIlllIll("magma_cream");
        J = llllIIIIlIIIlIlllIll("brewing_stand");
        K = llllIIIIlIIIlIlllIll("cauldron");
        L = llllIIIIlIIIlIlllIll("ender_eye");
        M = llllIIIIlIIIlIlllIll("speckled_melon");
        N = llllIIIIlIIIlIlllIll("spawn_egg");
        O = llllIIIIlIIIlIlllIll("experience_bottle");
        P = llllIIIIlIIIlIlllIll("fire_charge");
        Q = llllIIIIlIIIlIlllIll("writable_book");
        R = llllIIIIlIIIlIlllIll("written_book");
        S = llllIIIIlIIIlIlllIll("emerald");
        T = llllIIIIlIIIlIlllIll("item_frame");
        U = llllIIIIlIIIlIlllIll("flower_pot");
        V = llllIIIIlIIIlIlllIll("carrot");
        W = llllIIIIlIIIlIlllIll("potato");
        X = llllIIIIlIIIlIlllIll("baked_potato");
        Y = llllIIIIlIIIlIlllIll("poisonous_potato");
        Z = (llIlIIIIIlIIlIlIIlll)llllIIIIlIIIlIlllIll("map");
        aa = llllIIIIlIIIlIlllIll("golden_carrot");
        ab = llllIIIIlIIIlIlllIll("skull");
        ac = llllIIIIlIIIlIlllIll("carrot_on_a_stick");
        ad = llllIIIIlIIIlIlllIll("nether_star");
        ae = llllIIIIlIIIlIlllIll("pumpkin_pie");
        af = llllIIIIlIIIlIlllIll("fireworks");
        ag = llllIIIIlIIIlIlllIll("firework_charge");
        ah = (IlIIlIlIIIlIIlIlIlII)llllIIIIlIIIlIlllIll("enchanted_book");
        ai = llllIIIIlIIIlIlllIll("comparator");
        aj = llllIIIIlIIIlIlllIll("netherbrick");
        ak = llllIIIIlIIIlIlllIll("quartz");
        al = llllIIIIlIIIlIlllIll("tnt_minecart");
        am = llllIIIIlIIIlIlllIll("hopper_minecart");
        an = (llIIIlIlIllIIlIlIlII)llllIIIIlIIIlIlllIll("armor_stand");
        ao = llllIIIIlIIIlIlllIll("iron_horse_armor");
        ap = llllIIIIlIIIlIlllIll("golden_horse_armor");
        aq = llllIIIIlIIIlIlllIll("diamond_horse_armor");
        ar = llllIIIIlIIIlIlllIll("lead");
        as = llllIIIIlIIIlIlllIll("name_tag");
        at = llllIIIIlIIIlIlllIll("command_block_minecart");
        au = llllIIIIlIIIlIlllIll("record_13");
        av = llllIIIIlIIIlIlllIll("record_cat");
        aw = llllIIIIlIIIlIlllIll("record_blocks");
        ax = llllIIIIlIIIlIlllIll("record_chirp");
        ay = llllIIIIlIIIlIlllIll("record_far");
        az = llllIIIIlIIIlIlllIll("record_mall");
        aA = llllIIIIlIIIlIlllIll("record_mellohi");
        aB = llllIIIIlIIIlIlllIll("record_stal");
        aC = llllIIIIlIIIlIlllIll("record_strad");
        aD = llllIIIIlIIIlIlllIll("record_ward");
        aE = llllIIIIlIIIlIlllIll("record_11");
        aF = llllIIIIlIIIlIlllIll("record_wait");
        aG = llllIIIIlIIIlIlllIll("prismarine_shard");
        aH = llllIIIIlIIIlIlllIll("prismarine_crystals");
        aI = llllIIIIlIIIlIlllIll("banner");
    }
    
    private static IlIIIlIlIIIllIlIlIIl llllIIIIlIIIlIlllIll(final String s) {
        return (IlIIIlIlIIIllIlIlIIl)net.minecraft.llIllIlIIIIllIlIIllI.IlIIIlIlIIIllIlIlIIl.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lIllllIllIllIIllllll(s));
    }
}
