package net.minecraft.lIIIlllIIIllIIIllIII;

import net.minecraft.llllIIIIlIIIlIlllIll.*;
import net.minecraft.IlllllllIIIlIIIlIlII.*;

public class llllIIIIlIIIlIlllIll
{
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll llllIIIIlIIIlIlllIll;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IlIlIlIlIlllllllllIl;
    public static final IIllIIIlIIIIlIIlIIII llIllIIIIIllIlIIIIlI;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IlIIIlIlIIIllIlIlIIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IlIlIIIllIllIIIIIllI;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IllIIlllIIIIlllIIlIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll llllIIIlIlllIlIIIIIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lIIIIlIIIIIlllIllIII;
    public static final IllIIlllllIIllIIllIl lIIIlllIIIllIIIllIII;
    public static final cq llIIlIIIlIIIllIlIIIl;
    public static final IllIIlllllIIllIIllIl llIllIlIIIIllIlIIllI;
    public static final cq lIlIlIIIllIIllIIIllI;
    public static final bl IlIlIIIllIIllIlllllI;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IIIIlllIIIIIIlIIIlll;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll llllIIllllIlIlIIIIll;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IlIllIlIlIIIlIlIlIII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IIlllIIlIllIllIlIIll;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lllIIIIlllllIlIIllIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IlIlIIIIIIlllIlIllIl;
    public static final lIllIlIIIllllllIIlII IIllIIllIIIlIlIIIIlI;
    public static final lIllIlIIIllllllIIlII IIIlIIIlIlIIlllIIlll;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IlIlIIIlIIlIlIIlllIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IlllllllIIIlIIIlIlII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IIlIIIIlllIlllllIlII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IIIlIIlIIIIlllIlllII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IlIlIllllllllIIIIlII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IIlllIlIIllIlIlIlIIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll llIIIlIlIllIIlIlIlII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lllllIlIIIlIlIIlllII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lIllllllIIllIlIlIlII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll llIIlllIIlllIIllIllI;
    public static final v IIlllIIIlIlllIIlllII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IIlIIIIIllIlIIIlIIll;
    public static final dc llllllIllIllIlIllllI;
    public static final llIllIlIlIIIIIIIllII IIIllllllIllIIIlllIl;
    public static final v IlIIIlIIIllllIlIlIlI;
    public static final w IIIIIllIIIIlIIIIllIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IIIIIIIIIlllIllIlIlI;
    public static final y IIllllIIIlIIIIIIllIl;
    public static final lIIllIIIllllIlllIllI IlllIIIIlIIIlIlIlIIl;
    public static final lIIllIIIllllIlllIllI lllIllIIIllllllIllll;
    public static final IIlIIIIlllIlllllIlII llIllIlIlIIIIIIIllII;
    public static final IIlIIIIlllIlllllIlII IIlIlIlIIlIllIIIIIIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IllIllIIIIlIIlIlllII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IlIllllIIlIIlIlIlIll;
    public static final cc IllIllIlllIllllIIllI;
    public static final cc llIlIIIIIlIIlIlIIlll;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IlIIlIlIIIlIIlIlIlII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IllIlIIllIllIIlIllII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lIIlIIIlIllIlIllIIIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IIlIIIlllIllIllIlIII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lIlIlIlllIIlIlIlllIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll llIIIIIIlIllIIlIIIll;
    public static final IIlIlIllllIlllIIIIll lIIIIlIlIllllIIlIllI;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll llIIIlIlllIllIIlIllI;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IlIIllIIllIIllIIlIIl;
    public static final IIlIIIIIllIlIIIlIIll lllllIIIIIlIlIIIIIIl;
    public static final bh IllIIlllllIIllIIllIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lIllIIIIIlllIIlIIllI;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lIlIIlllIIlIIlIlllIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll llIIIllIlIllIllIIIIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IIIllIIIlIlIIllIIIlI;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IIlllIIlllIIIlIlllII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IlIIlllllIIllIIlllll;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lllllIIlIlIIIlIlIIIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IIlllllIllIllIlIlIII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll llllIllllIllllIlIlII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IIlIlIllllIlllIIIIll;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lIIllIIIllllIlllIllI;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IllIlIllIllIlllIIlll;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IIllIIIlIIlIlIlIIIII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll llIllIIlllllllllllll;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lllllIIllIlIllIllllI;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IlIIIIIlIIllIIlIlIll;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IllllIIlIlIllIIIllII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lllllIIIIIlIIlllIlIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IlIllllIIIlIllIlIIll;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lIIIIIlIlIIIlIIIIlIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IIllIIIlIIIIlIIlIIII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IIIllIIllIIIIIIlIIlI;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IIIIIIIllllIlIIIIIII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IIlllIIIllIllIIlIlIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll llIlllIlllllIIllIIII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lllllIlIlIlllIlllIlI;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IlIllllIIlIllIlIlIll;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lllIlIIIIIlIlllllIlI;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll llIlIIIIllIlIIlIlIII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IIIIIlllIlIIIIIIIllI;
    public static final llIIIlIlIllIIlIlIlII llllllIIIIIIIlllIIll;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IIlIlllIlIlllIlIllll;
    public static final bj lIllllIllIllIIllllll;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lllIIIIlIlIllIIlIIIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IllIlllIllIIIIllllII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lIllIlIIIllllllIIlII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IlIllIIllIIlIIIIlIIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lIIlllIlllllIIlllIll;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lIllIIlIlIlllllIIIII;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll lIIlIIIIIIIlIIlIlIIl;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll IlIIlllIIlIlllllIIlI;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll llllIlIllllIIlIIlIlI;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll a;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll b;
    public static final ab c;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll d;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll e;
    public static final be f;
    public static final be g;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll h;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll i;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll j;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll k;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll l;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll m;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll n;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll o;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll p;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll q;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll r;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll s;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll t;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll u;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll v;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll w;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll x;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll y;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll z;
    public static final e A;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll B;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll C;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll D;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll E;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll F;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll G;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll H;
    public static final IIlllIIIlIlllIIlllII I;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll J;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll K;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll L;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll M;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll N;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll O;
    public static final cc P;
    public static final cc Q;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll R;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll S;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll T;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll U;
    public static final dj V;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll W;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll X;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll Y;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll Z;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll aa;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll ab;
    public static final IlIllIlIlIIIlIlIlIII ac;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll ad;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll ae;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll af;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll ag;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll ah;
    public static final ca ai;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll aj;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll ak;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll al;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll am;
    public static final ay an;
    public static final ay ao;
    public static final lllIllIIIllllllIllll ap;
    public static final lllIllIIIllllllIllll aq;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll ar;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll as;
    public static final lllIlIIIIIlIlllllIlI at;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll au;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll av;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll aw;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll ax;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll ay;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll az;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll aA;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll aB;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll aC;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll aD;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll aE;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll aF;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll aG;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll aH;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll aI;
    public static final lIIlIIIlIllIlIllIIIl aJ;
    public static final ck aK;
    public static final cl aL;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll aM;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll aN;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll aO;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll aP;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll aQ;
    public static final net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll aR;
    public static final cc aS;
    public static final cc aT;
    
    static {
        if (!net.minecraft.lIIIlllIIIllIIIllIII.IlIlIlIlIlllllllllIl.llllIIIIlIIIlIlllIll()) {
            throw new RuntimeException("Accessed Blocks before Bootstrap!");
        }
        llllIIIIlIIIlIlllIll = llllIIIIlIIIlIlllIll("air");
        IlIlIlIlIlllllllllIl = llllIIIIlIIIlIlllIll("stone");
        llIllIIIIIllIlIIIIlI = (IIllIIIlIIIIlIIlIIII)llllIIIIlIIIlIlllIll("grass");
        IlIIIlIlIIIllIlIlIIl = llllIIIIlIIIlIlllIll("dirt");
        IlIlIIIllIllIIIIIllI = llllIIIIlIIIlIlllIll("cobblestone");
        IllIIlllIIIIlllIIlIl = llllIIIIlIIIlIlllIll("planks");
        llllIIIlIlllIlIIIIIl = llllIIIIlIIIlIlllIll("sapling");
        lIIIIlIIIIIlllIllIII = llllIIIIlIIIlIlllIll("bedrock");
        lIIIlllIIIllIIIllIII = (IllIIlllllIIllIIllIl)llllIIIIlIIIlIlllIll("flowing_water");
        llIIlIIIlIIIllIlIIIl = (cq)llllIIIIlIIIlIlllIll("water");
        llIllIlIIIIllIlIIllI = (IllIIlllllIIllIIllIl)llllIIIIlIIIlIlllIll("flowing_lava");
        lIlIlIIIllIIllIIIllI = (cq)llllIIIIlIIIlIlllIll("lava");
        IlIlIIIllIIllIlllllI = (bl)llllIIIIlIIIlIlllIll("sand");
        IIIIlllIIIIIIlIIIlll = llllIIIIlIIIlIlllIll("gravel");
        llllIIllllIlIlIIIIll = llllIIIIlIIIlIlllIll("gold_ore");
        IlIllIlIlIIIlIlIlIII = llllIIIIlIIIlIlllIll("iron_ore");
        IIlllIIlIllIllIlIIll = llllIIIIlIIIlIlllIll("coal_ore");
        lllIIIIlllllIlIIllIl = llllIIIIlIIIlIlllIll("log");
        IlIlIIIIIIlllIlIllIl = llllIIIIlIIIlIlllIll("log2");
        IIllIIllIIIlIlIIIIlI = (lIllIlIIIllllllIIlII)llllIIIIlIIIlIlllIll("leaves");
        IIIlIIIlIlIIlllIIlll = (lIllIlIIIllllllIIlII)llllIIIIlIIIlIlllIll("leaves2");
        IlIlIIIlIIlIlIIlllIl = llllIIIIlIIIlIlllIll("sponge");
        IlllllllIIIlIIIlIlII = llllIIIIlIIIlIlllIll("glass");
        IIlIIIIlllIlllllIlII = llllIIIIlIIIlIlllIll("lapis_ore");
        IIIlIIlIIIIlllIlllII = llllIIIIlIIIlIlllIll("lapis_block");
        IlIlIllllllllIIIIlII = llllIIIIlIIIlIlllIll("dispenser");
        IIlllIlIIllIlIlIlIIl = llllIIIIlIIIlIlllIll("sandstone");
        llIIIlIlIllIIlIlIlII = llllIIIIlIIIlIlllIll("noteblock");
        lllllIlIIIlIlIIlllII = llllIIIIlIIIlIlllIll("bed");
        lIllllllIIllIlIlIlII = llllIIIIlIIIlIlllIll("golden_rail");
        llIIlllIIlllIIllIllI = llllIIIIlIIIlIlllIll("detector_rail");
        IIlllIIIlIlllIIlllII = (v)llllIIIIlIIIlIlllIll("sticky_piston");
        IIlIIIIIllIlIIIlIIll = llllIIIIlIIIlIlllIll("web");
        llllllIllIllIlIllllI = (dc)llllIIIIlIIIlIlllIll("tallgrass");
        IIIllllllIllIIIlllIl = (llIllIlIlIIIIIIIllII)llllIIIIlIIIlIlllIll("deadbush");
        IlIIIlIIIllllIlIlIlI = (v)llllIIIIlIIIlIlllIll("piston");
        IIIIIllIIIIlIIIIllIl = (w)llllIIIIlIIIlIlllIll("piston_head");
        IIIIIIIIIlllIllIlIlI = llllIIIIlIIIlIlllIll("wool");
        IIllllIIIlIIIIIIllIl = (y)llllIIIIlIIIlIlllIll("piston_extension");
        IlllIIIIlIIIlIlIlIIl = (lIIllIIIllllIlllIllI)llllIIIIlIIIlIlllIll("yellow_flower");
        lllIllIIIllllllIllll = (lIIllIIIllllIlllIllI)llllIIIIlIIIlIlllIll("red_flower");
        llIllIlIlIIIIIIIllII = (IIlIIIIlllIlllllIlII)llllIIIIlIIIlIlllIll("brown_mushroom");
        IIlIlIlIIlIllIIIIIIl = (IIlIIIIlllIlllllIlII)llllIIIIlIIIlIlllIll("red_mushroom");
        IllIllIIIIlIIlIlllII = llllIIIIlIIIlIlllIll("gold_block");
        IlIllllIIlIIlIlIlIll = llllIIIIlIIIlIlllIll("iron_block");
        IllIllIlllIllllIIllI = (cc)llllIIIIlIIIlIlllIll("double_stone_slab");
        llIlIIIIIlIIlIlIIlll = (cc)llllIIIIlIIIlIlllIll("stone_slab");
        IlIIlIlIIIlIIlIlIlII = llllIIIIlIIIlIlllIll("brick_block");
        IllIlIIllIllIIlIllII = llllIIIIlIIIlIlllIll("tnt");
        lIIlIIIlIllIlIllIIIl = llllIIIIlIIIlIlllIll("bookshelf");
        IIlIIIlllIllIllIlIII = llllIIIIlIIIlIlllIll("mossy_cobblestone");
        lIlIlIlllIIlIlIlllIl = llllIIIIlIIIlIlllIll("obsidian");
        llIIIIIIlIllIIlIIIll = llllIIIIlIIIlIlllIll("torch");
        lIIIIlIlIllllIIlIllI = (IIlIlIllllIlllIIIIll)llllIIIIlIIIlIlllIll("fire");
        llIIIlIlllIllIIlIllI = llllIIIIlIIIlIlllIll("mob_spawner");
        IlIIllIIllIIllIIlIIl = llllIIIIlIIIlIlllIll("oak_stairs");
        lllllIIIIIlIlIIIIIIl = (IIlIIIIIllIlIIIlIIll)llllIIIIlIIIlIlllIll("chest");
        IllIIlllllIIllIIllIl = (bh)llllIIIIlIIIlIlllIll("redstone_wire");
        lIllIIIIIlllIIlIIllI = llllIIIIlIIIlIlllIll("diamond_ore");
        lIlIIlllIIlIIlIlllIl = llllIIIIlIIIlIlllIll("diamond_block");
        llIIIllIlIllIllIIIIl = llllIIIIlIIIlIlllIll("crafting_table");
        IIIllIIIlIlIIllIIIlI = llllIIIIlIIIlIlllIll("wheat");
        IIlllIIlllIIIlIlllII = llllIIIIlIIIlIlllIll("farmland");
        IlIIlllllIIllIIlllll = llllIIIIlIIIlIlllIll("furnace");
        lllllIIlIlIIIlIlIIIl = llllIIIIlIIIlIlllIll("lit_furnace");
        IIlllllIllIllIlIlIII = llllIIIIlIIIlIlllIll("standing_sign");
        llllIllllIllllIlIlII = llllIIIIlIIIlIlllIll("wooden_door");
        IIlIlIllllIlllIIIIll = llllIIIIlIIIlIlllIll("spruce_door");
        lIIllIIIllllIlllIllI = llllIIIIlIIIlIlllIll("birch_door");
        IllIlIllIllIlllIIlll = llllIIIIlIIIlIlllIll("jungle_door");
        IIllIIIlIIlIlIlIIIII = llllIIIIlIIIlIlllIll("acacia_door");
        llIllIIlllllllllllll = llllIIIIlIIIlIlllIll("dark_oak_door");
        lllllIIllIlIllIllllI = llllIIIIlIIIlIlllIll("ladder");
        IlIIIIIlIIllIIlIlIll = llllIIIIlIIIlIlllIll("rail");
        IllllIIlIlIllIIIllII = llllIIIIlIIIlIlllIll("stone_stairs");
        lllllIIIIIlIIlllIlIl = llllIIIIlIIIlIlllIll("wall_sign");
        IlIllllIIIlIllIlIIll = llllIIIIlIIIlIlllIll("lever");
        lIIIIIlIlIIIlIIIIlIl = llllIIIIlIIIlIlllIll("stone_pressure_plate");
        IIllIIIlIIIIlIIlIIII = llllIIIIlIIIlIlllIll("iron_door");
        IIIllIIllIIIIIIlIIlI = llllIIIIlIIIlIlllIll("wooden_pressure_plate");
        IIIIIIIllllIlIIIIIII = llllIIIIlIIIlIlllIll("redstone_ore");
        IIlllIIIllIllIIlIlIl = llllIIIIlIIIlIlllIll("lit_redstone_ore");
        llIlllIlllllIIllIIII = llllIIIIlIIIlIlllIll("unlit_redstone_torch");
        lllllIlIlIlllIlllIlI = llllIIIIlIIIlIlllIll("redstone_torch");
        IlIllllIIlIllIlIlIll = llllIIIIlIIIlIlllIll("stone_button");
        lllIlIIIIIlIlllllIlI = llllIIIIlIIIlIlllIll("snow_layer");
        llIlIIIIllIlIIlIlIII = llllIIIIlIIIlIlllIll("ice");
        IIIIIlllIlIIIIIIIllI = llllIIIIlIIIlIlllIll("snow");
        llllllIIIIIIIlllIIll = (llIIIlIlIllIIlIlIlII)llllIIIIlIIIlIlllIll("cactus");
        IIlIlllIlIlllIlIllll = llllIIIIlIIIlIlllIll("clay");
        lIllllIllIllIIllllll = (bj)llllIIIIlIIIlIlllIll("reeds");
        lllIIIIlIlIllIIlIIIl = llllIIIIlIIIlIlllIll("jukebox");
        IllIlllIllIIIIllllII = llllIIIIlIIIlIlllIll("fence");
        lIllIlIIIllllllIIlII = llllIIIIlIIIlIlllIll("spruce_fence");
        IlIllIIllIIlIIIIlIIl = llllIIIIlIIIlIlllIll("birch_fence");
        lIIlllIlllllIIlllIll = llllIIIIlIIIlIlllIll("jungle_fence");
        lIllIIlIlIlllllIIIII = llllIIIIlIIIlIlllIll("dark_oak_fence");
        lIIlIIIIIIIlIIlIlIIl = llllIIIIlIIIlIlllIll("acacia_fence");
        IlIIlllIIlIlllllIIlI = llllIIIIlIIIlIlllIll("pumpkin");
        llllIlIllllIIlIIlIlI = llllIIIIlIIIlIlllIll("netherrack");
        a = llllIIIIlIIIlIlllIll("soul_sand");
        b = llllIIIIlIIIlIlllIll("glowstone");
        c = (ab)llllIIIIlIIIlIlllIll("portal");
        d = llllIIIIlIIIlIlllIll("lit_pumpkin");
        e = llllIIIIlIIIlIlllIll("cake");
        f = (be)llllIIIIlIIIlIlllIll("unpowered_repeater");
        g = (be)llllIIIIlIIIlIlllIll("powered_repeater");
        h = llllIIIIlIIIlIlllIll("trapdoor");
        i = llllIIIIlIIIlIlllIll("monster_egg");
        j = llllIIIIlIIIlIlllIll("stonebrick");
        k = llllIIIIlIIIlIlllIll("brown_mushroom_block");
        l = llllIIIIlIIIlIlllIll("red_mushroom_block");
        m = llllIIIIlIIIlIlllIll("iron_bars");
        n = llllIIIIlIIIlIlllIll("glass_pane");
        o = llllIIIIlIIIlIlllIll("melon_block");
        p = llllIIIIlIIIlIlllIll("pumpkin_stem");
        q = llllIIIIlIIIlIlllIll("melon_stem");
        r = llllIIIIlIIIlIlllIll("vine");
        s = llllIIIIlIIIlIlllIll("fence_gate");
        t = llllIIIIlIIIlIlllIll("spruce_fence_gate");
        u = llllIIIIlIIIlIlllIll("birch_fence_gate");
        v = llllIIIIlIIIlIlllIll("jungle_fence_gate");
        w = llllIIIIlIIIlIlllIll("dark_oak_fence_gate");
        x = llllIIIIlIIIlIlllIll("acacia_fence_gate");
        y = llllIIIIlIIIlIlllIll("brick_stairs");
        z = llllIIIIlIIIlIlllIll("stone_brick_stairs");
        A = (e)llllIIIIlIIIlIlllIll("mycelium");
        B = llllIIIIlIIIlIlllIll("waterlily");
        C = llllIIIIlIIIlIlllIll("nether_brick");
        D = llllIIIIlIIIlIlllIll("nether_brick_fence");
        E = llllIIIIlIIIlIlllIll("nether_brick_stairs");
        F = llllIIIIlIIIlIlllIll("nether_wart");
        G = llllIIIIlIIIlIlllIll("enchanting_table");
        H = llllIIIIlIIIlIlllIll("brewing_stand");
        I = (IIlllIIIlIlllIIlllII)llllIIIIlIIIlIlllIll("cauldron");
        J = llllIIIIlIIIlIlllIll("end_portal");
        K = llllIIIIlIIIlIlllIll("end_portal_frame");
        L = llllIIIIlIIIlIlllIll("end_stone");
        M = llllIIIIlIIIlIlllIll("dragon_egg");
        N = llllIIIIlIIIlIlllIll("redstone_lamp");
        O = llllIIIIlIIIlIlllIll("lit_redstone_lamp");
        P = (cc)llllIIIIlIIIlIlllIll("double_wooden_slab");
        Q = (cc)llllIIIIlIIIlIlllIll("wooden_slab");
        R = llllIIIIlIIIlIlllIll("cocoa");
        S = llllIIIIlIIIlIlllIll("sandstone_stairs");
        T = llllIIIIlIIIlIlllIll("emerald_ore");
        U = llllIIIIlIIIlIlllIll("ender_chest");
        V = (dj)llllIIIIlIIIlIlllIll("tripwire_hook");
        W = llllIIIIlIIIlIlllIll("tripwire");
        X = llllIIIIlIIIlIlllIll("emerald_block");
        Y = llllIIIIlIIIlIlllIll("spruce_stairs");
        Z = llllIIIIlIIIlIlllIll("birch_stairs");
        aa = llllIIIIlIIIlIlllIll("jungle_stairs");
        ab = llllIIIIlIIIlIlllIll("command_block");
        ac = (IlIllIlIlIIIlIlIlIII)llllIIIIlIIIlIlllIll("beacon");
        ad = llllIIIIlIIIlIlllIll("cobblestone_wall");
        ae = llllIIIIlIIIlIlllIll("flower_pot");
        af = llllIIIIlIIIlIlllIll("carrots");
        ag = llllIIIIlIIIlIlllIll("potatoes");
        ah = llllIIIIlIIIlIlllIll("wooden_button");
        ai = (ca)llllIIIIlIIIlIlllIll("skull");
        aj = llllIIIIlIIIlIlllIll("anvil");
        ak = llllIIIIlIIIlIlllIll("trapped_chest");
        al = llllIIIIlIIIlIlllIll("light_weighted_pressure_plate");
        am = llllIIIIlIIIlIlllIll("heavy_weighted_pressure_plate");
        an = (ay)llllIIIIlIIIlIlllIll("unpowered_comparator");
        ao = (ay)llllIIIIlIIIlIlllIll("powered_comparator");
        ap = (lllIllIIIllllllIllll)llllIIIIlIIIlIlllIll("daylight_detector");
        aq = (lllIllIIIllllllIllll)llllIIIIlIIIlIlllIll("daylight_detector_inverted");
        ar = llllIIIIlIIIlIlllIll("redstone_block");
        as = llllIIIIlIIIlIlllIll("quartz_ore");
        at = (lllIlIIIIIlIlllllIlI)llllIIIIlIIIlIlllIll("hopper");
        au = llllIIIIlIIIlIlllIll("quartz_block");
        av = llllIIIIlIIIlIlllIll("quartz_stairs");
        aw = llllIIIIlIIIlIlllIll("activator_rail");
        ax = llllIIIIlIIIlIlllIll("dropper");
        ay = llllIIIIlIIIlIlllIll("stained_hardened_clay");
        az = llllIIIIlIIIlIlllIll("barrier");
        aA = llllIIIIlIIIlIlllIll("iron_trapdoor");
        aB = llllIIIIlIIIlIlllIll("hay_block");
        aC = llllIIIIlIIIlIlllIll("carpet");
        aD = llllIIIIlIIIlIlllIll("hardened_clay");
        aE = llllIIIIlIIIlIlllIll("coal_block");
        aF = llllIIIIlIIIlIlllIll("packed_ice");
        aG = llllIIIIlIIIlIlllIll("acacia_stairs");
        aH = llllIIIIlIIIlIlllIll("dark_oak_stairs");
        aI = llllIIIIlIIIlIlllIll("slime");
        aJ = (lIIlIIIlIllIlIllIIIl)llllIIIIlIIIlIlllIll("double_plant");
        aK = (ck)llllIIIIlIIIlIlllIll("stained_glass");
        aL = (cl)llllIIIIlIIIlIlllIll("stained_glass_pane");
        aM = llllIIIIlIIIlIlllIll("prismarine");
        aN = llllIIIIlIIIlIlllIll("sea_lantern");
        aO = llllIIIIlIIIlIlllIll("standing_banner");
        aP = llllIIIIlIIIlIlllIll("wall_banner");
        aQ = llllIIIIlIIIlIlllIll("red_sandstone");
        aR = llllIIIIlIIIlIlllIll("red_sandstone_stairs");
        aS = (cc)llllIIIIlIIIlIlllIll("double_stone_slab2");
        aT = (cc)llllIIIIlIIIlIlllIll("stone_slab2");
    }
    
    private static net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll llllIIIIlIIIlIlllIll(final String s) {
        return (net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll)net.minecraft.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lIllllIllIllIIllllll(s));
    }
}
