package net.minecraft.llIllIlIIIIllIlIIllI.llllIIIIlIIIlIlllIll;

import net.minecraft.lIIIlllIIIllIIIllIII.*;
import net.minecraft.llIllIlIIIIllIlIIllI.*;
import net.minecraft.llllIIIIlIIIlIlllIll.*;

public class IIIIlllIIIIIIlIIIlll
{
    public void llllIIIIlIIIlIlllIll(final llllIIIIlIIIlIlllIll llllIIIIlIIIlIlllIll) {
        for (int i = 0; i < 16; ++i) {
            llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IIIIIIIIIlllIllIlIlI, 1, i), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, 15 - i), new lllIIIIlIlIllIIlIIIl(IlIIIlIlIIIllIlIlIIl.llllIIIIlIIIlIlllIll(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IIIIIIIIIlllIllIlIlI), 1, 0));
            llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.ay, 8, 15 - i), "###", "#X#", "###", '#', new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.aD), 'X', new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, i));
            llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.aK, 8, 15 - i), "###", "#X#", "###", '#', new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlllllllIIIlIIIlIlII), 'X', new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, i));
            llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.aL, 16, i), "###", "###", '#', new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.aK, 1, i));
        }
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.IlIlIIIllIllIIIIIllI.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlllIIIIlIIIlIlIlIIl, 1, llIllIIlllllllllllll.llllIIIIlIIIlIlllIll.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llllIIllllIlIlIIIIll.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.lllIllIIIllllllIllll, 1, llIllIIlllllllllllll.IlIlIlIlIlllllllllIl.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 3, IlIlIlIlIlllllllllIl.llllIIIIlIIIlIlllIll.llIllIIIIIllIlIIIIlI()), IIllIIllIIIlIlIIIIlI.b);
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 2, IlIlIlIlIlllllllllIl.llllIIIlIlllIlIIIIIl.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llllIIllllIlIlIIIIll.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llllIIIIlIIIlIlllIll.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 2, IlIlIlIlIlllllllllIl.IlIlIlIlIlllllllllIl.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llllIIllllIlIlIIIIll.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.IlIlIIIllIllIIIIIllI.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 2, IlIlIlIlIlllllllllIl.IllIIlllIIIIlllIIlIl.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.IIIIlllIIIIIIlIIIlll.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llllIIIIlIIIlIlllIll.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 2, IlIlIlIlIlllllllllIl.lIIIIlIIIIIlllIllIII.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.IlIllIlIlIIIlIlIlIII.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llllIIIIlIIIlIlllIll.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 2, IlIlIlIlIlllllllllIl.lIIIlllIIIllIIIllIII.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.lIIIIlIIIIIlllIllIII.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llllIIIIlIIIlIlllIll.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 3, IlIlIlIlIlllllllllIl.lIIIlllIIIllIIIllIII.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.IlIllIlIlIIIlIlIlIII.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llllIIIIlIIIlIlllIll.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llllIIIIlIIIlIlllIll.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 2, IlIlIlIlIlllllllllIl.IlIIIlIlIIIllIlIlIIl.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.lIlIlIIIllIIllIIIllI.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llllIIIIlIIIlIlllIll.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 2, IlIlIlIlIlllllllllIl.llIIlIIIlIIIllIlIIIl.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.lIlIlIIIllIIllIIIllI.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.IIIIlllIIIIIIlIIIlll.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 2, IlIlIlIlIlllllllllIl.llIllIlIIIIllIlIIllI.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.lIlIlIIIllIIllIIIllI.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llllIIllllIlIlIIIIll.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 2, IlIlIlIlIlllllllllIl.llIllIIIIIllIlIIIIlI.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llIllIlIIIIllIlIIllI.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llllIIIlIlllIlIIIIIl.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 3, IlIlIlIlIlllllllllIl.llIllIIIIIllIlIIIIlI.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.lIlIlIIIllIIllIIIllI.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llllIIllllIlIlIIIIll.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llllIIIlIlllIlIIIIIl.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 4, IlIlIlIlIlllllllllIl.llIllIIIIIllIlIIIIlI.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.lIlIlIIIllIIllIIIllI.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llllIIllllIlIlIIIIll.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llllIIllllIlIlIIIIll.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llllIIIIlIIIlIlllIll.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.IlIIIlIlIIIllIlIlIIl.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.lllIllIIIllllllIllll, 1, llIllIIlllllllllllll.llIllIIIIIllIlIIIIlI.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llIllIIIIIllIlIIIIlI.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.lllIllIIIllllllIllll, 1, llIllIIlllllllllllll.IlIIIlIlIIIllIlIlIIl.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.lIIIlllIIIllIIIllIII.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.lllIllIIIllllllIllll, 1, llIllIIlllllllllllll.IlIlIIIllIllIIIIIllI.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llllIIllllIlIlIIIIll.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.lllIllIIIllllllIllll, 1, llIllIIlllllllllllll.IllIIlllIIIIlllIIlIl.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.IlIlIlIlIlllllllllIl.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.lllIllIIIllllllIllll, 1, llIllIIlllllllllllll.llllIIIlIlllIlIIIIIl.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.lIIIlllIIIllIIIllIII.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.lllIllIIIllllllIllll, 1, llIllIIlllllllllllll.lIIIIlIIIIIlllIllIII.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.llllIIIlIlllIlIIIIIl.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.lllIllIIIllllllIllll, 1, llIllIIlllllllllllll.lIIIlllIIIllIIIllIII.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.lIIIlllIIIllIIIllIII.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.lllIllIIIllllllIllll, 1, llIllIIlllllllllllll.llIIlIIIlIIIllIlIIIl.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 2, IlIlIlIlIlllllllllIl.IlIlIIIllIllIIIIIllI.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.aJ, 1, lIlIlIlllIIlIlIlllIl.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 2, IlIlIlIlIlllllllllIl.llIllIIIIIllIlIIIIlI.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.aJ, 1, lIlIlIlllIIlIlIlllIl.IlIlIlIlIlllllllllIl.IlIlIlIlIlllllllllIl()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 2, IlIlIlIlIlllllllllIl.llllIIllllIlIlIIIIll.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.aJ, 1, lIlIlIlllIIlIlIlllIl.IlIlIIIllIllIIIIIllI.IlIlIlIlIlllllllllIl()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 2, IlIlIlIlIlllllllllIl.llllIIIlIlllIlIIIIIl.llIllIIIIIllIlIIIIlI()), new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.aJ, 1, lIlIlIlllIIlIlIlllIl.IllIIlllIIIIlllIIlIl.IlIlIlIlIlllllllllIl()));
        for (int j = 0; j < 16; ++j) {
            llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.aC, 3, j), "##", '#', new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IIIIIIIIIlllIllIlIlI, 1, j));
        }
    }
}
