package net.minecraft.llIllIlIIIIllIlIIllI.llllIIIIlIIIlIlllIll;

import net.minecraft.lIIIlllIIIllIIIllIII.*;
import net.minecraft.llllIIIIlIIIlIlllIll.*;
import net.minecraft.llIllIlIIIIllIlIIllI.*;

public class IlIlIIIllIIllIlllllI
{
    public void llllIIIIlIIIlIlllIll(final llllIIIIlIIIlIlllIll llllIIIIlIIIlIlllIll) {
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.lllllIIIIIlIlIIIIIIl), "###", "# #", "###", '#', net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IllIIlllIIIIlllIIlIl);
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.ak), "#-", '#', net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.lllllIIIIIlIlIIIIIIl, '-', net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.V);
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.U), "###", "#E#", "###", '#', net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.lIlIlIlllIIlIlIlllIl, 'E', IIllIIllIIIlIlIIIIlI.L);
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIIlllllIIllIIlllll), "###", "# #", "###", '#', net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIlIIIllIllIIIIIllI);
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.llIIIllIlIllIllIIIIl), "##", "##", '#', net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IllIIlllIIIIlllIIlIl);
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IIlllIlIIllIlIlIlIIl), "##", "##", '#', new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIlIIIllIIllIlllllI, 1, bm.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl()));
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.aQ), "##", "##", '#', new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIlIIIllIIllIlllllI, 1, bm.IlIlIlIlIlllllllllIl.IlIlIlIlIlllllllllIl()));
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IIlllIlIIllIlIlIlIIl, 4, bo.llIllIIIIIllIlIIIIlI.IlIlIlIlIlllllllllIl()), "##", "##", '#', new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IIlllIlIIllIlIlIlIIl, 1, bo.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl()));
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.aQ, 4, ax.llIllIIIIIllIlIIIIlI.IlIlIlIlIlllllllllIl()), "##", "##", '#', new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.aQ, 1, ax.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl()));
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IIlllIlIIllIlIlIlIIl, 1, bo.IlIlIlIlIlllllllllIl.IlIlIlIlIlllllllllIl()), "#", "#", '#', new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.llIlIIIIIlIIlIlIIlll, 1, cy.IlIlIlIlIlllllllllIl.IlIlIlIlIlllllllllIl()));
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.aQ, 1, ax.IlIlIlIlIlllllllllIl.IlIlIlIlIlllllllllIl()), "#", "#", '#', new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.aT, 1, da.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl()));
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.au, 1, am.IlIlIlIlIlllllllllIl.IlIlIlIlIlllllllllIl()), "#", "#", '#', new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.llIlIIIIIlIIlIlIIlll, 1, cy.lIIIIlIIIIIlllIllIII.IlIlIlIlIlllllllllIl()));
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.au, 2, am.llIllIIIIIllIlIIIIlI.IlIlIlIlIlllllllllIl()), "#", "#", '#', new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.au, 1, am.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl()));
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.j, 4), "##", "##", '#', new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl, 1, cu.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl()));
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.j, 1, cv.llIllIlIlIIIIIIIllII), "#", "#", '#', new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.llIlIIIIIlIIlIlIIlll, 1, cy.IllIIlllIIIIlllIIlIl.IlIlIlIlIlllllllllIl()));
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.j, 1, cv.IlllIIIIlIIIlIlIlIIl), net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.j, net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.r);
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IIlIIIlllIllIllIlIII, 1), net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIlIIIllIllIIIIIllI, net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.r);
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.m, 16), "###", "###", '#', IIllIIllIIIlIlIIIIlI.llIIlIIIlIIIllIlIIIl);
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.n, 16), "###", "###", '#', net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlllllllIIIlIIIlIlII);
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.N, 1), " R ", "RGR", " R ", 'R', IIllIIllIIIlIlIIIIlI.IIIIIIIllllIlIIIIIII, 'G', net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.b);
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.ac, 1), "GGG", "GSG", "OOO", 'G', net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlllllllIIIlIIIlIlII, 'S', IIllIIllIIIlIlIIIIlI.ad, 'O', net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.lIlIlIlllIIlIlIlllIl);
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.C, 1), "NN", "NN", 'N', IIllIIllIIIlIlIIIIlI.aj);
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl, 2, cu.IlIIIlIlIIIllIlIlIIl.IlIlIlIlIlllllllllIl()), "CQ", "QC", 'C', net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIlIIIllIllIIIIIllI, 'Q', IIllIIllIIIlIlIIIIlI.ak);
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl, 1, cu.IlIlIlIlIlllllllllIl.IlIlIlIlIlllllllllIl()), new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl, 1, cu.IlIIIlIlIIIllIlIlIIl.IlIlIlIlIlllllllllIl()), IIllIIllIIIlIlIIIIlI.ak);
        llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl, 2, cu.IllIIlllIIIIlllIIlIl.IlIlIlIlIlllllllllIl()), new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl, 1, cu.IlIIIlIlIIIllIlIlIIl.IlIlIlIlIlllllllllIl()), net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIlIIIllIllIIIIIllI);
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIIIlIlIIIllIlIlIIl, 4, IlIllllIIlIIlIlIlIll.IlIlIlIlIlllllllllIl.IlIlIlIlIlllllllllIl()), "DG", "GD", 'D', new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIIIlIlIIIllIlIlIIl, 1, IlIllllIIlIIlIlIlIll.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl()), 'G', net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IIIIlllIIIIIIlIIIlll);
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl, 4, cu.IlIlIIIllIllIIIIIllI.IlIlIlIlIlllllllllIl()), "SS", "SS", 'S', new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl, 1, cu.IlIIIlIlIIIllIlIlIIl.IlIlIlIlIlllllllllIl()));
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl, 4, cu.llIllIIIIIllIlIIIIlI.IlIlIlIlIlllllllllIl()), "SS", "SS", 'S', new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl, 1, cu.IlIlIlIlIlllllllllIl.IlIlIlIlIlllllllllIl()));
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl, 4, cu.llllIIIlIlllIlIIIIIl.IlIlIlIlIlllllllllIl()), "SS", "SS", 'S', new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.IlIlIlIlIlllllllllIl, 1, cu.IllIIlllIIIIlllIIlIl.IlIlIlIlIlllllllllIl()));
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.aM, 1, ah.IIllllIIIlIIIIIIllIl), "SS", "SS", 'S', IIllIIllIIIlIlIIIIlI.aG);
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.aM, 1, ah.IlllIIIIlIIIlIlIlIIl), "SSS", "SSS", "SSS", 'S', IIllIIllIIIlIlIIIIlI.aG);
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.aM, 1, ah.lllIllIIIllllllIllll), "SSS", "SIS", "SSS", 'S', IIllIIllIIIlIlIIIIlI.aG, 'I', new lllIIIIlIlIllIIlIIIl(IIllIIllIIIlIlIIIIlI.a, 1, IlIlIlIlIlllllllllIl.IlIllIlIlIIIlIlIlIII.llIllIIIIIllIlIIIIlI()));
        llllIIIIlIIIlIlllIll.llllIIIIlIIIlIlllIll(new lllIIIIlIlIllIIlIIIl(net.minecraft.lIIIlllIIIllIIIllIII.llllIIIIlIIIlIlllIll.aN, 1, 0), "SCS", "CCC", "SCS", 'S', IIllIIllIIIlIlIIIIlI.aG, 'C', IIllIIllIIIlIlIIIIlI.aH);
    }
}
