package net.minecraft.IIIlIIlIIIIlllIlllII.IlIlIIIllIllIIIIIllI;

public class llllIIIlIlllIlIIIIIl
{
    public final float llllIIIIlIIIlIlllIll;
    public final float IlIlIlIlIlllllllllIl;
    public final float llIllIIIIIllIlIIIIlI;
    public final float IlIIIlIlIIIllIlIlIIl;
    public final float IlIlIIIllIllIIIIIllI;
    public final float IllIIlllIIIIlllIIlIl;
    public final float llllIIIlIlllIlIIIIIl;
    public final float lIIIIlIIIIIlllIllIII;
    public final float lIIIlllIIIllIIIllIII;
    public final float llIIlIIIlIIIllIlIIIl;
    public final float llIllIlIIIIllIlIIllI;
    public final float lIlIlIIIllIIllIIIllI;
    public final float IlIlIIIllIIllIlllllI;
    public final float IIIIlllIIIIIIlIIIlll;
    public final float llllIIllllIlIlIIIIll;
    public final float IlIllIlIlIIIlIlIlIII;
    public final int IIlllIIlIllIllIlIIll;
    public final boolean lllIIIIlllllIlIIllIl;
    public final boolean IlIlIIIIIIlllIlIllIl;
    public final int IIllIIllIIIlIlIIIIlI;
    public final boolean IIIlIIIlIlIIlllIIlll;
    public final boolean IlIlIIIlIIlIlIIlllIl;
    public final boolean IlllllllIIIlIIIlIlII;
    public final boolean IIlIIIIlllIlllllIlII;
    public final boolean IIIlIIlIIIIlllIlllII;
    public final boolean IlIlIllllllllIIIIlII;
    public final boolean IIlllIlIIllIlIlIlIIl;
    public final int llIIIlIlIllIIlIlIlII;
    public final boolean lllllIlIIIlIlIIlllII;
    public final int lIllllllIIllIlIlIlII;
    public final boolean llIIlllIIlllIIllIllI;
    public final int IIlllIIIlIlllIIlllII;
    public final int IIlIIIIIllIlIIIlIIll;
    public final int llllllIllIllIlIllllI;
    public final int IIIllllllIllIIIlllIl;
    public final int IlIIIlIIIllllIlIlIlI;
    public final int IIIIIllIIIIlIIIIllIl;
    public final int IIIIIIIIIlllIllIlIlI;
    public final int IIllllIIIlIIIIIIllIl;
    public final int IlllIIIIlIIIlIlIlIIl;
    public final int lllIllIIIllllllIllll;
    public final int llIllIlIlIIIIIIIllII;
    public final int IIlIlIlIIlIllIIIIIIl;
    public final int IllIllIIIIlIIlIlllII;
    public final int IlIllllIIlIIlIlIlIll;
    public final int IllIllIlllIllllIIllI;
    public final int llIlIIIIIlIIlIlIIlll;
    public final int IlIIlIlIIIlIIlIlIlII;
    public final int IllIlIIllIllIIlIllII;
    public final int lIIlIIIlIllIlIllIIIl;
    public final int IIlIIIlllIllIllIlIII;
    public final int lIlIlIlllIIlIlIlllIl;
    public final int llIIIIIIlIllIIlIIIll;
    public final int lIIIIlIlIllllIIlIllI;
    public final int llIIIlIlllIllIIlIllI;
    public final int IlIIllIIllIIllIIlIIl;
    public final int lllllIIIIIlIlIIIIIIl;
    public final int IllIIlllllIIllIIllIl;
    public final int lIllIIIIIlllIIlIIllI;
    public final int lIlIIlllIIlIIlIlllIl;
    public final int llIIIllIlIllIllIIIIl;
    public final int IIIllIIIlIlIIllIIIlI;
    public final int IIlllIIlllIIIlIlllII;
    public final int IlIIlllllIIllIIlllll;
    public final int lllllIIlIlIIIlIlIIIl;
    public final int IIlllllIllIllIlIlIII;
    public final int llllIllllIllllIlIlII;
    public final int IIlIlIllllIlllIIIIll;
    public final int lIIllIIIllllIlllIllI;
    public final int IllIlIllIllIlllIIlll;
    public final int IIllIIIlIIlIlIlIIIII;
    public final int llIllIIlllllllllllll;
    public final int lllllIIllIlIllIllllI;
    public final int IlIIIIIlIIllIIlIlIll;
    public final int IllllIIlIlIllIIIllII;
    public final int lllllIIIIIlIIlllIlIl;
    public final int IlIllllIIIlIllIlIIll;
    public final int lIIIIIlIlIIIlIIIIlIl;
    
    private llllIIIlIlllIlIIIIIl(final lIIIIlIIIIIlllIllIII liiiIlIIIIIlllIllIII) {
        this.llllIIIIlIIIlIlllIll = liiiIlIIIIIlllIllIII.IlIlIlIlIlllllllllIl;
        this.IlIlIlIlIlllllllllIl = liiiIlIIIIIlllIllIII.llIllIIIIIllIlIIIIlI;
        this.llIllIIIIIllIlIIIIlI = liiiIlIIIIIlllIllIII.IlIIIlIlIIIllIlIlIIl;
        this.IlIIIlIlIIIllIlIlIIl = liiiIlIIIIIlllIllIII.IlIlIIIllIllIIIIIllI;
        this.IlIlIIIllIllIIIIIllI = liiiIlIIIIIlllIllIII.IllIIlllIIIIlllIIlIl;
        this.IllIIlllIIIIlllIIlIl = liiiIlIIIIIlllIllIII.llllIIIlIlllIlIIIIIl;
        this.llllIIIlIlllIlIIIIIl = liiiIlIIIIIlllIllIII.lIIIIlIIIIIlllIllIII;
        this.lIIIIlIIIIIlllIllIII = liiiIlIIIIIlllIllIII.lIIIlllIIIllIIIllIII;
        this.lIIIlllIIIllIIIllIII = liiiIlIIIIIlllIllIII.llIIlIIIlIIIllIlIIIl;
        this.llIIlIIIlIIIllIlIIIl = liiiIlIIIIIlllIllIII.llIllIlIIIIllIlIIllI;
        this.llIllIlIIIIllIlIIllI = liiiIlIIIIIlllIllIII.lIlIlIIIllIIllIIIllI;
        this.lIlIlIIIllIIllIIIllI = liiiIlIIIIIlllIllIII.IlIlIIIllIIllIlllllI;
        this.IlIlIIIllIIllIlllllI = liiiIlIIIIIlllIllIII.IIIIlllIIIIIIlIIIlll;
        this.IIIIlllIIIIIIlIIIlll = liiiIlIIIIIlllIllIII.llllIIllllIlIlIIIIll;
        this.llllIIllllIlIlIIIIll = liiiIlIIIIIlllIllIII.IlIllIlIlIIIlIlIlIII;
        this.IlIllIlIlIIIlIlIlIII = liiiIlIIIIIlllIllIII.IIlllIIlIllIllIlIIll;
        this.IIlllIIlIllIllIlIIll = liiiIlIIIIIlllIllIII.lllIIIIlllllIlIIllIl;
        this.lllIIIIlllllIlIIllIl = liiiIlIIIIIlllIllIII.IlIlIIIIIIlllIlIllIl;
        this.IlIlIIIIIIlllIlIllIl = liiiIlIIIIIlllIllIII.IIllIIllIIIlIlIIIIlI;
        this.IIllIIllIIIlIlIIIIlI = liiiIlIIIIIlllIllIII.IIIlIIIlIlIIlllIIlll;
        this.IIIlIIIlIlIIlllIIlll = liiiIlIIIIIlllIllIII.IlIlIIIlIIlIlIIlllIl;
        this.IlIlIIIlIIlIlIIlllIl = liiiIlIIIIIlllIllIII.IlllllllIIIlIIIlIlII;
        this.IlllllllIIIlIIIlIlII = liiiIlIIIIIlllIllIII.IIlIIIIlllIlllllIlII;
        this.IIlIIIIlllIlllllIlII = liiiIlIIIIIlllIllIII.IIIlIIlIIIIlllIlllII;
        this.IIIlIIlIIIIlllIlllII = liiiIlIIIIIlllIllIII.IlIlIllllllllIIIIlII;
        this.IlIlIllllllllIIIIlII = liiiIlIIIIIlllIllIII.IIlllIlIIllIlIlIlIIl;
        this.IIlllIlIIllIlIlIlIIl = liiiIlIIIIIlllIllIII.llIIIlIlIllIIlIlIlII;
        this.llIIIlIlIllIIlIlIlII = liiiIlIIIIIlllIllIII.lllllIlIIIlIlIIlllII;
        this.lllllIlIIIlIlIIlllII = liiiIlIIIIIlllIllIII.lIllllllIIllIlIlIlII;
        this.lIllllllIIllIlIlIlII = liiiIlIIIIIlllIllIII.llIIlllIIlllIIllIllI;
        this.llIIlllIIlllIIllIllI = liiiIlIIIIIlllIllIII.IIlllIIIlIlllIIlllII;
        this.IIlllIIIlIlllIIlllII = liiiIlIIIIIlllIllIII.IIlIIIIIllIlIIIlIIll;
        this.IIlIIIIIllIlIIIlIIll = liiiIlIIIIIlllIllIII.llllllIllIllIlIllllI;
        this.llllllIllIllIlIllllI = liiiIlIIIIIlllIllIII.IIIllllllIllIIIlllIl;
        this.IIIllllllIllIIIlllIl = liiiIlIIIIIlllIllIII.IlIIIlIIIllllIlIlIlI;
        this.IlIIIlIIIllllIlIlIlI = liiiIlIIIIIlllIllIII.IIIIIllIIIIlIIIIllIl;
        this.IIIIIllIIIIlIIIIllIl = liiiIlIIIIIlllIllIII.IIIIIIIIIlllIllIlIlI;
        this.IIIIIIIIIlllIllIlIlI = liiiIlIIIIIlllIllIII.IIllllIIIlIIIIIIllIl;
        this.IIllllIIIlIIIIIIllIl = liiiIlIIIIIlllIllIII.IlllIIIIlIIIlIlIlIIl;
        this.IlllIIIIlIIIlIlIlIIl = liiiIlIIIIIlllIllIII.lllIllIIIllllllIllll;
        this.lllIllIIIllllllIllll = liiiIlIIIIIlllIllIII.llIllIlIlIIIIIIIllII;
        this.llIllIlIlIIIIIIIllII = liiiIlIIIIIlllIllIII.IIlIlIlIIlIllIIIIIIl;
        this.IIlIlIlIIlIllIIIIIIl = liiiIlIIIIIlllIllIII.IllIllIIIIlIIlIlllII;
        this.IllIllIIIIlIIlIlllII = liiiIlIIIIIlllIllIII.IlIllllIIlIIlIlIlIll;
        this.IlIllllIIlIIlIlIlIll = liiiIlIIIIIlllIllIII.IllIllIlllIllllIIllI;
        this.IllIllIlllIllllIIllI = liiiIlIIIIIlllIllIII.llIlIIIIIlIIlIlIIlll;
        this.llIlIIIIIlIIlIlIIlll = liiiIlIIIIIlllIllIII.IlIIlIlIIIlIIlIlIlII;
        this.IlIIlIlIIIlIIlIlIlII = liiiIlIIIIIlllIllIII.IllIlIIllIllIIlIllII;
        this.IllIlIIllIllIIlIllII = liiiIlIIIIIlllIllIII.lIIlIIIlIllIlIllIIIl;
        this.lIIlIIIlIllIlIllIIIl = liiiIlIIIIIlllIllIII.IIlIIIlllIllIllIlIII;
        this.IIlIIIlllIllIllIlIII = liiiIlIIIIIlllIllIII.lIlIlIlllIIlIlIlllIl;
        this.lIlIlIlllIIlIlIlllIl = liiiIlIIIIIlllIllIII.llIIIIIIlIllIIlIIIll;
        this.llIIIIIIlIllIIlIIIll = liiiIlIIIIIlllIllIII.lIIIIlIlIllllIIlIllI;
        this.lIIIIlIlIllllIIlIllI = liiiIlIIIIIlllIllIII.llIIIlIlllIllIIlIllI;
        this.llIIIlIlllIllIIlIllI = liiiIlIIIIIlllIllIII.IlIIllIIllIIllIIlIIl;
        this.IlIIllIIllIIllIIlIIl = liiiIlIIIIIlllIllIII.lllllIIIIIlIlIIIIIIl;
        this.lllllIIIIIlIlIIIIIIl = liiiIlIIIIIlllIllIII.IllIIlllllIIllIIllIl;
        this.IllIIlllllIIllIIllIl = liiiIlIIIIIlllIllIII.lIllIIIIIlllIIlIIllI;
        this.lIllIIIIIlllIIlIIllI = liiiIlIIIIIlllIllIII.lIlIIlllIIlIIlIlllIl;
        this.lIlIIlllIIlIIlIlllIl = liiiIlIIIIIlllIllIII.llIIIllIlIllIllIIIIl;
        this.llIIIllIlIllIllIIIIl = liiiIlIIIIIlllIllIII.IIIllIIIlIlIIllIIIlI;
        this.IIIllIIIlIlIIllIIIlI = liiiIlIIIIIlllIllIII.IIlllIIlllIIIlIlllII;
        this.IIlllIIlllIIIlIlllII = liiiIlIIIIIlllIllIII.IlIIlllllIIllIIlllll;
        this.IlIIlllllIIllIIlllll = liiiIlIIIIIlllIllIII.lllllIIlIlIIIlIlIIIl;
        this.lllllIIlIlIIIlIlIIIl = liiiIlIIIIIlllIllIII.IIlllllIllIllIlIlIII;
        this.IIlllllIllIllIlIlIII = liiiIlIIIIIlllIllIII.llllIllllIllllIlIlII;
        this.llllIllllIllllIlIlII = liiiIlIIIIIlllIllIII.IIlIlIllllIlllIIIIll;
        this.IIlIlIllllIlllIIIIll = liiiIlIIIIIlllIllIII.lIIllIIIllllIlllIllI;
        this.lIIllIIIllllIlllIllI = liiiIlIIIIIlllIllIII.IllIlIllIllIlllIIlll;
        this.IllIlIllIllIlllIIlll = liiiIlIIIIIlllIllIII.IIllIIIlIIlIlIlIIIII;
        this.IIllIIIlIIlIlIlIIIII = liiiIlIIIIIlllIllIII.llIllIIlllllllllllll;
        this.llIllIIlllllllllllll = liiiIlIIIIIlllIllIII.lllllIIllIlIllIllllI;
        this.lllllIIllIlIllIllllI = liiiIlIIIIIlllIllIII.IlIIIIIlIIllIIlIlIll;
        this.IlIIIIIlIIllIIlIlIll = liiiIlIIIIIlllIllIII.IllllIIlIlIllIIIllII;
        this.IllllIIlIlIllIIIllII = liiiIlIIIIIlllIllIII.lllllIIIIIlIIlllIlIl;
        this.lllllIIIIIlIIlllIlIl = liiiIlIIIIIlllIllIII.IlIllllIIIlIllIlIIll;
        this.IlIllllIIIlIllIlIIll = liiiIlIIIIIlllIllIII.lIIIIIlIlIIIlIIIIlIl;
        this.lIIIIIlIlIIIlIIIIlIl = liiiIlIIIIIlllIllIII.IIllIIIlIIIIlIIlIIII;
    }
}
